#!/usr/bin/env bash

FS_CUSTOMIZE_BASH_DIR=$(readlink -f $(dirname "${0}"))

if ! [ -e "${FS_CUSTOMIZE_BASH_DIR}/bashrc" ]; then
	echo "${FS_CUSTOMIZE_BASH_DIR}/bashrc does not exist. Check your download of this repository." >&2
	exit 1
fi

# check if this file can be successfully included

. "${FS_CUSTOMIZE_BASH_DIR}/bashrc" > /dev/null

if [ $? -ne 0 ]; then
	echo "bashrc has not been successfully sourced. Check your bash installation." >&2
	exit 1
fi

# some options available in this script now since conf.fsbash is sourced

echo "Installation of ${FS_CUSTOMIZED_BASH_MAGIC} version ${FS_CUSTOMIZED_BASH_VERSION}"
echo
echo -e "Warning: This installation will "'\e[1;41mReplace\e[0;0m'" your current .bashrc file (but with backup)."
echo "Enter 'Y' within 10 seconds to continue installation."
echo

FS_CUSTOMIZE_BASH_INSTALL_CONFIRMATION=false

if read -t 10 FS_CUSTOMIZE_BASH_REPLY; then
	case "$FS_CUSTOMIZE_BASH_REPLY" in
		[Yy])
			FS_CUSTOMIZE_BASH_INSTALL_CONFIRMATION=true
			;;
		*)
			:
			;;
	esac
fi

if ! $FS_CUSTOMIZE_BASH_INSTALL_CONFIRMATION; then
	echo "Installation not confirmed. Exiting."
	exit 2
fi

FS_CUSTOMIZE_BASH_INSTALL_BASHRC="$HOME/.bashrc"

if [ -e ${FS_CUSTOMIZE_BASH_INSTALL_BASHRC} ]; then
	mv ${FS_CUSTOMIZE_BASH_INSTALL_BASHRC} ${FS_CUSTOMIZE_BASH_INSTALL_BASHRC}.backup
	echo "Made backup of original bashrc file to ${FS_CUSTOMIZE_BASH_INSTALL_BASHRC}.backup"
fi

echo "Following contents are written to ${FS_CUSTOMIZE_BASH_INSTALL_BASHRC}."
echo
echo '[[ "$-" != *i* ]] && return' | tee ${FS_CUSTOMIZE_BASH_INSTALL_BASHRC}
echo '. '"${FS_CUSTOMIZE_BASH_DIR}"'/bashrc' | tee -a ${FS_CUSTOMIZE_BASH_INSTALL_BASHRC}
echo

FS_CUSTOMIZE_BASH_INSTALL_PROFILE="$HOME/.bash_profile"

if [ -e "$HOME/.profile" ]; then
	FS_CUSTOMIZE_BASH_INSTALL_PROFILE="$HOME/.profile"
fi

if [ -e "$FS_CUSTOMIZE_BASH_INSTALL_PROFILE" ] && ( cat "$FS_CUSTOMIZE_BASH_INSTALL_PROFILE" | grep -q -F ".bashrc" ); then
	echo "Found '.bashrc' in ${FS_CUSTOMIZE_BASH_INSTALL_PROFILE}, not modifying ${FS_CUSTOMIZE_BASH_INSTALL_PROFILE}."
else
	if ! [ -z "$TERMUX_VERSION" ]; then
		echo "Note: Termux is source-ing ~/.bashrc in /prefix/usr/etc/profile (at least in default install of some version)."
		echo "This is not typical use case since ~/.bashrc is rather user-specific and shouldn't be touched in system-wide configuration file."
		echo
		echo "You may examine the /prefix/usr/etc/profile to see if it loads your user-specific .bashrc. if so you may simply comment it out."
		echo
	fi

	echo "Following contents are appended to ${FS_CUSTOMIZE_BASH_INSTALL_PROFILE}."
	echo

	if ! [ -e "$FS_CUSTOMIZE_BASH_INSTALL_PROFILE" ]; then
		echo '#!/usr/bin/env bash' | tee ${FS_CUSTOMIZE_BASH_INSTALL_PROFILE}
		echo | tee -a ${FS_CUSTOMIZE_BASH_INSTALL_PROFILE}
		echo '# This file is generated by '"${FS_CUSTOMIZED_BASH_MAGIC}"' version '"${FS_CUSTOMIZED_BASH_VERSION}"'.' | tee -a ${FS_CUSTOMIZE_BASH_INSTALL_PROFILE}
		echo | tee -a ${FS_CUSTOMIZE_BASH_INSTALL_PROFILE}
		echo '# Typically .bashrc is sourced on a non-login shell and is not sourced on a login shell.'
		echo '# Only .profile (or bash specific .bash_profile) is sourced on a login shell.' | tee -a ${FS_CUSTOMIZE_BASH_INSTALL_PROFILE}
		echo '# By adding this file, the .bashrc is sourced on a login shell as well by source-ing that file in .profile.' | tee -a ${FS_CUSTOMIZE_BASH_INSTALL_PROFILE}
		echo | tee -a ${FS_CUSTOMIZE_BASH_INSTALL_PROFILE}
	else
		echo | tee -a ${FS_CUSTOMIZE_BASH_INSTALL_PROFILE}
		echo '# Following line is added by '"${FS_CUSTOMIZED_BASH_MAGIC}"' version '"${FS_CUSTOMIZED_BASH_VERSION}"' for source-ing the bashrc in a non-login shell.'| tee -a ${FS_CUSTOMIZE_BASH_INSTALL_PROFILE}
	fi

	echo '[ -n "$BASH_VERSION" ] && [ -r "$HOME/.bashrc" ] && . "$HOME/.bashrc"' | tee -a ${FS_CUSTOMIZE_BASH_INSTALL_PROFILE}
	echo
fi

echo "Installation complete."

exit 0
